# Generated by Django 3.1.4 on 2020-12-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atm',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
