# Generated by Django 3.1.4 on 2021-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_bank_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
